/* Autogenerated with kurento-module-creator */

#ifndef __RTSP_TO_RTP_ENDPOINT_IMPL_HPP__
#define __RTSP_TO_RTP_ENDPOINT_IMPL_HPP__

#include "FilterImpl.hpp"
#include "RtspToRtpEndpoint.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include <functional>

namespace kurento
{
namespace module
{
namespace rtsptortpendpoint
{
class RtspToRtpEndpointImpl;
} /* rtsptortpendpoint */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::rtsptortpendpoint::RtspToRtpEndpointImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace rtsptortpendpoint
{

class RtspToRtpEndpointImpl : public FilterImpl, public virtual RtspToRtpEndpoint
{

public:

  RtspToRtpEndpointImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline,
           const std::string &ipcamUri, int port);

  virtual ~RtspToRtpEndpointImpl() = default;

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* rtsptortpendpoint */
} /* module */
} /* kurento */

#endif /*  __RTSP_TO_RTP_ENDPOINT_IMPL_HPP__ */
