#!/bin/sh

set -e

printf "Building Gstreamer module for KMS..\n"

DIRECTORY="build"

if [ ! -d "$DIRECTORY" ]; then
    printf '%s\n' "Error: Please build the project before rebuild!"
    exit 1
fi

# build the module
cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr && make && sudo make install && sudo cp src/server/libkmsfiletortspendpointmodule.so /usr/lib/x86_64-linux-gnu/kurento/modules/

# Generate JS client project
cmake .. -DGENERATE_JS_CLIENT_PROJECT=TRUE && cp -r js/. ../../kurento-tutorial-node/kurento-chroma/node_modules/kurento-module-filetortspendpoint

printf "\n\n\nPlease restart Kurento media server to take effect!!\n----------------------------------------\n"
