/* Autogenerated with kurento-module-creator */

#ifndef __RTMP_TO_RTSP_ENDPOINT_IMPL_HPP__
#define __RTMP_TO_RTSP_ENDPOINT_IMPL_HPP__

#include "FilterImpl.hpp"
#include "RtmpToRtspEndpoint.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include <functional>

namespace kurento
{
namespace module
{
namespace rtmptortspendpoint
{
class RtmpToRtspEndpointImpl;
} /* rtmptortspendpoint */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::rtmptortspendpoint::RtmpToRtspEndpointImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace rtmptortspendpoint
{

class RtmpToRtspEndpointImpl : public FilterImpl, public virtual RtmpToRtspEndpoint
{

public:

  RtmpToRtspEndpointImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline,
                          const std::string &rtmpUri, int port);

  virtual ~RtmpToRtspEndpointImpl() = default;

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* rtmptortspendpoint */
} /* module */
} /* kurento */

#endif /*  __RTMP_TO_RTSP_ENDPOINT_IMPL_HPP__ */
