#!/bin/sh

set -e

printf "Building Gstreamer module for KMS..\n"

DIRECTORY="build"

if [ ! -d "$DIRECTORY" ]; then
    printf '%s\n' "Error: Please build the project before rebuild!"
    exit 1
fi

# build the module
cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr && make && sudo make install && sudo cp src/server/libkmsrtsptortpendpointmodule.so /usr/lib/x86_64-linux-gnu/kurento/modules/
